# This is an example of /etc/nerdctl/nerdctl.toml .
# Unrelated to the daemon's /etc/containerd/config.toml .

# debug          = false
debug_full     = true
address        = "/home/buxton/Documents/pdtpartners/nix-snapshotter/build/containerd/state/containerd.sock"
# namespace      = "k8s.io"
snapshotter    = "nix"
cgroup_manager = "none"
# hosts_dir      = ["/etc/containerd/certs.d", "/etc/docker/certs.d"]
experimental   = true
data_root      = "/home/buxton/Documents/pdtpartners/nix-snapshotter/build/nerdctl/root/"
cni_netconfpath= "/home/buxton/Documents/pdtpartners/nix-snapshotter/build/cni/"
cni_path= "/home/buxton/Documents/pdtpartners/nix-snapshotter/build/cni-2/"