apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
  - name: redis
    image: hinshun/redis:nix
    args: [ "--protected-mode", "no" ]
    ports:
      - containerPort: 6379
        name: client
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis
  ports:
  - name: client
    port: 6379
    nodePort: 30000
