name: static_analysis

on:
  push:
  pull_request:

jobs:
  go_lint_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Go Linter
        run: nix develop